id = "catppuccin-icons"
name = "Catppuccin Icons"
version = "1.23.1"
schema_version = 1
description = "ðŸ¦Š Soothing pastel icons for Zed"
repository = "https://github.com/catppuccin/zed-icons"
authors = ["Catppuccin <releases@catppuccin.com>"]
themes = []
icon_themes = ["icon_themes/catppuccin-icons.json"]
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
