id = "xml"
name = "XML"
version = "0.0.9"
schema_version = 1
description = "XML syntax support."
repository = "https://github.com/sweetppro/zed-xml"
authors = ["sweetppro"]
themes = []
icon_themes = []
languages = ["languages/xml"]
capabilities = []

[lib]

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
rev = "863dbc381f44f6c136a399e684383b977bb2beaa"
path = "xml"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
