[colors.primary]
background = '#19120f'
foreground = '#efdfda'
 
[colors.cursor]
text = '#efdfda'
cursor = '#dac1b8' 
 
[colors.vi_mode_cursor]
text = '#19120f'
cursor = '#ffb798' 
 
[colors.search.matches]
foreground = '#54433c' 
background = '#d0cc64' 
 
[colors.search.focused_match]
foreground = '#54433c' 
background = '#ffb798' 
 
[colors.footer_bar]
foreground = '#54433c' 
background = '#efdfda' 
 
[colors.hints.start]
foreground = '#54433c' 
background = '#f0bba5' 
 
[colors.hints.end]
foreground = '#54433c' 
background = '#f0bba5' 
 
[colors.selection]
text = '#19120f'
background = '#ffb798'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb798' 
yellow = '#954925' 
blue = '#ffb798' 
magenta = '#d0cc64' 
cyan = '#f0bba5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 