[colors.primary]
background = '#131315'
foreground = '#e5e2e4'
 
[colors.cursor]
text = '#e5e2e4'
cursor = '#c6c6cd' 
 
[colors.vi_mode_cursor]
text = '#131315'
cursor = '#c0c5e1' 
 
[colors.search.matches]
foreground = '#46464d' 
background = '#dac499' 
 
[colors.search.focused_match]
foreground = '#46464d' 
background = '#c0c5e1' 
 
[colors.footer_bar]
foreground = '#46464d' 
background = '#e5e2e4' 
 
[colors.hints.start]
foreground = '#46464d' 
background = '#c5c6d2' 
 
[colors.hints.end]
foreground = '#46464d' 
background = '#c5c6d2' 
 
[colors.selection]
text = '#131315'
background = '#c0c5e1'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#c0c5e1' 
yellow = '#575d76' 
blue = '#c0c5e1' 
magenta = '#dac499' 
cyan = '#c5c6d2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 