id = "make"
name = "Make"
version = "1.1.1"
schema_version = 1
description = "Makefile syntax highlighting"
repository = "https://github.com/caius/zed-make"
authors = ["Caius Durling <dev@caius.name>", "d1y <chenhonzhou@gmail.com>", "Marshall Bowers <elliott.codes@gmail.com>", "Luke Naylor <luke@grahamnaylor.net>", "Igor TÃ¡mara <igor.tamara@gmail.com>", "Michael Alexander <michael.alexander@karlstorz.com>"]
themes = []
icon_themes = []
languages = ["languages/make"]
capabilities = []

[lib]

[grammars.make]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-make"
rev = "5e9e8f8ff3387b0edcaa90f46ddf3629f4cfeb1d"

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
